name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libzmq3-dev

    - name: Build client
      run: make -C client

    - name: Build server
      run: make -C server

    - name: Rename binaries
      run: |
        mv client/client client-linux
        mv server/server server-linux

    - name: Upload client binary
      uses: softprops/action-gh-release@v2
      with:
        files: client-linux
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    - name: Upload server binary
      uses: softprops/action-gh-release@v2
      with:
        files: server-linux
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
